name = "Spirit Biomes' ATM10"
author = "Vee + ATMTeam"
version = "4.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8b6da4a0d01a802b740c0321cb1dbb96334b3d2024c6efc40be7d606bc770d3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"

[options]
datapack-folder = "config/openloader/data"
