name = "Spirit Biomes' ATM10"
author = "Vee + ATMTeam"
version = "4.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa6a3ea605c0fbabc1458d27564c834710b26951da560be6cb23bc875adde954"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
