name = "Spirit Biomes' ATM10"
author = "Vee + ATMTeam"
version = "4.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b75091411222912a60214fb8eba2f5503ea6d9c5947bb7e5795aee6c5388649c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"

[options]
datapack-folder = "config/openloader/data"
