name = "Spirit Biomes' ATM10"
author = "Vee + ATMTeam"
version = "4.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09a1770a5d932b9010f54d8f57c39c5e1570c539dae98abd79c0f64d9138ff33"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"

[options]
datapack-folder = "config/openloader/data"
