name = "Spirit Biomes' ATM10"
author = "Vee + ATMTeam"
version = "4.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3af5a4c01f97abd6f77991290eecbacd9e60ca36b9b6f2ed1ef8ef352a19b77"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"

[options]
datapack-folder = "config/openloader/data"
