name = "Spirit Biomes' ATM10"
author = "Vee + ATMTeam"
version = "4.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "353f61116f7c6ef704355b9006309c0ee6919bac3fd7048b4191a98ee352ae20"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"

[options]
datapack-folder = "config/openloader/data"
