["quantum computer"]
	#Define the maximum dimensions of the Quantum Computer Multiblock.
	#Range: 5 ~ 12
	quantumComputerMaxSize = 7
	#Define the maximum amount of multi threaders per Quantum Computer Multiblock.
	#Range: 4 ~ 16
	quantumComputerAcceleratorThreads = 12
	#Define the maximum amount of multi threaders per Quantum Computer Multiblock.
	#Range: 1 ~ 2
	quantumComputerMaxMultiThreaders = 1
	#Define the maximum amount of Data Entanglers per Quantum Computer Multiblock.
	#Range: 1 ~ 2
	quantumComputermaxDataEntanglers = 1
	#Define the multiplication factor of the multi threaders.
	#Range: 2 ~ 8
	quantumComputerMultiThreaderMultiplication = 6
	#Define the multiplication factor of the data entanglers.
	#Range: 2 ~ 8
	quantumComputerDataEntanglerMultiplication = 6
